using System;
using UnityEngine;

namespace FiresCore.Logging
{
    // Core's own console banners, rendered through the shared Banner engine.
    //
    //   PrintBig()  → hearth campfire under a spark-lit sky with the FIRES CORE
    //                 brand. Fires at the very top of Setup, before any consumer
    //                 mod loads, so the family stack opens with the hearth.
    //   Print()     → compact flame over a status frame ("HEARTH LIT"). Fires
    //                 once at first WorldStart.
    //
    // Art generated by Tools\gen_fires_banner.ps1 (spec: FiresUnifiedCore).
    // Color zones: spark sky (Yellow/White), flame crown (Yellow/DarkYellow),
    // flame body (Red/DarkYellow), logs (DarkRed/DarkGray), brand (Cyan/White).
    internal static class FiresCoreBanner
    {
        private static bool s_compactPrinted;

        public static void PrintBig()
        {
            try
            {
                EmitHeader("Fires Unified Core Loading...");
                Banner.Print(ToSegments(s_bigLines));
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"[FiresUnifiedCore] Big banner failed: {ex.Message}");
            }
        }

        public static void Print()
        {
            if (s_compactPrinted) return;
            s_compactPrinted = true;
            try
            {
                EmitHeader("Fires Unified Core Loaded.");
                Banner.Print(s_compactLines);
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"[FiresUnifiedCore] Compact banner failed: {ex.Message}");
            }
        }

        // Routes the one-line header through Core's BepInEx log source (not
        // Debug.Log) so it prints once, colored by FiresLogColorPatch via the
        // Fires source name, without a raw white stdout duplicate.
        private static void EmitHeader(string text)
        {
            if (FiresUnifiedCore.Log != null) FiresUnifiedCore.Log.LogInfo(text);
            else Debug.Log($"[FiresUnifiedCore] {text}");
        }

        private static Banner.Segment[][] ToSegments((string text, ConsoleColor color)[] lines)
        {
            var result = new Banner.Segment[lines.Length][];
            for (int i = 0; i < lines.Length; i++)
                result[i] = new[] { new Banner.Segment(lines[i].text, lines[i].color) };
            return result;
        }

        // Compact banner — flame over a hearth-status frame. 31-char frame body
        // (3 lead + ╔ + 26 ═ + ╗); 🔥 is a surrogate pair, but the console
        // ADVANCES ONE column for it (no VS16), however wide the font paints the glyph, so this row pads it as one cell.
        private static readonly Banner.Segment[][] s_compactLines =
        {
            new[] { new Banner.Segment("                .",            ConsoleColor.Yellow) },
            new[] { new Banner.Segment("               /█\\",          ConsoleColor.Yellow) },
            new[] { new Banner.Segment("              /███\\",         ConsoleColor.DarkYellow) },
            new[] { new Banner.Segment("             (█████)",         ConsoleColor.Red) },
            new[] { new Banner.Segment("            ▂▂█████▂▂",        ConsoleColor.DarkRed) },
            new[] { new Banner.Segment("   ╔══════════════════════════╗", ConsoleColor.DarkGray) },
            new[]
            {
                new Banner.Segment("   ║   ",              ConsoleColor.DarkGray),
                new Banner.Segment("[",                    ConsoleColor.Gray),
                new Banner.Segment("██████████████████",   ConsoleColor.Green),
                new Banner.Segment("]",                    ConsoleColor.Gray),
                new Banner.Segment("   ║",                 ConsoleColor.DarkGray),
            },
            new[]
            {
                new Banner.Segment("   ║      ",           ConsoleColor.DarkGray),
                new Banner.Segment("🔥 HEARTH LIT",        ConsoleColor.Yellow),
                new Banner.Segment("        ║",             ConsoleColor.DarkGray),
            },
            new[] { new Banner.Segment("   ╚══════════════════════════╝", ConsoleColor.DarkGray) },
            new[] { new Banner.Segment("    FIRES UNIFIED CORE",       ConsoleColor.Cyan) },
            new Banner.Segment[0],
            new[] { new Banner.Segment("   Fires Unified Core Loaded", ConsoleColor.Magenta) },
        };

        private static readonly (string text, ConsoleColor color)[] s_bigLines =
        {
            ("", ConsoleColor.Gray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%", ConsoleColor.White),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%:%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%", ConsoleColor.White),
            ("%%%%%%%%%%%%%%@@%@%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%:%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%", ConsoleColor.White),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.White),
            ("%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%++%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@@%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%+==+%%%%%%%%%%%%:%%%@%%%%%%%%%%%%%%@%%%@%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%@%+====+%%%%%%@%%%%%%%%%%%%%%%@%%%%%%%%@%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%@%%%%%%%%%%%%%@%%%%%%%%%%%:%%%%%%%%%%%%+======+%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%@%+========+%%%%@%@%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%@%%%%%%%%%@%%%%%%%%%%%%%%%%%+==========+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%+============+%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%@%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%+==============+%%@%%%%%%%%%%%%@%%%%%@%%%%%%%%%%%%%@%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%+=======::=======+@%%%%%%%%%%:%%%%%%%%%%%@%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%@%%@%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%+=======:..:=======+%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%+=======:....:=======+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%+========......:=======+%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%@%%%%%%%%%%%%@%%%%%%%%%%@%%%%%%%%%%%%+=======:.......========#%%@%%%%@%%%%%%%%%%%%%%%%%%%%%@%%%%%%%", ConsoleColor.Yellow),
            ("%@%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%+======:........:======+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@@%%%%@", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%+====:..........:====+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%+==:............:===#%%%%%%%%%%%%%%%%%%@%%%%%%%%@%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%+==..............:=+%%%%%%%%%%%%%%%@%@%%%%%%%%%%%@%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%@%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%+:...............+%%%%%@%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%++:...............=+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%+===:.............-==++%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%@%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%+======:...........-=====+%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%++========:.........-========+%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%@%%%%%%%%%%%%%%%%@%%%%@%%+==========:.........==========++%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Yellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%+===========:...........===========+%%%%%%%@%%%%%@%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%@%%@%%%%%%%%%%%%+==========:.............===========#%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%+=========:...............=========+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%+=======:.................========#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%+======:...................======+%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%+=====:..................:-=====#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%+=======:..............:-======+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%@%%%%%%%@%%%%%%%%%%%%%%%%%%+========:..........:-========#%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%@%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%+==========:......:-=========+%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%@%%%%+===========:..:-===========#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%@%%@%%%@%%%%%%%%%%%+=============-============+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%", ConsoleColor.DarkYellow),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%*+***@##########################@%%%%%%%%%@%%%%%%%%%%%%%%%%%@%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%+++++++++++***@%%%%%%%%%%%%%%%*++=======+%%%%%%%%%%%%%%%%%%%%%%@%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%@***+++==++++++====---------------==+%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("@%%%@@%%%%%%%%%%%%%%%%%%%%%%%=====-------------===+++++=-====+*@%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%==========++*%%%%%%%%%%%@***++++++++++++*%%%@%%%%%%%%%%%%%@%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%@@***+++*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Cyan),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.White),
            ("%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Cyan),
            ("%::::::::%:::::%+::::::::-%%%:::::::-%%-::::::-+%%%%%%%-:::::::-%%%%-::::::-%%%::::::::-%%%-:::::::%", ConsoleColor.White),
            ("%:.......%:....%+.........:%%.......:%:........:%%%%%%:....:....-%+:........:%%.........:@%:.......%", ConsoleColor.Cyan),
            ("%:....---%:....%+....:-....%%....:---%....:-....%@%%%%....:%:...:%-....-:....%%....:-....-%:....---@", ConsoleColor.White),
            ("%:....---%:....%+....::....%%....:---%:....:----%%%%%%....:%:...:%:....+:....@%....:-....-%:....---%", ConsoleColor.Cyan),
            ("%:......:%:....%+........:-%%.......:%-:......:-%%%%@@....:%-----%:....+:....@%.........-%%:......:%", ConsoleColor.White),
            ("%:....::-%:....%+....::...:%%.....::-%%%-::.....-%%%%%....:%-----%:....+:....@%....:-....-%:....:::%", ConsoleColor.Cyan),
            ("%:....%%%%:....%+....:-....%%....:%%%%:...:-....:%%%%%....:%:...:%-....=:....@%....:%....-%:....%%%%", ConsoleColor.White),
            ("%:....%%%%:....%+....:-....%%.....:::%:...:-....:%%%%%:...:-....:%-....::....%%....:%....-%:....:::-", ConsoleColor.Cyan),
            ("%:....%%%%:....%+....:-....%%........%-:.......:-%%%%%-:.......:-%%:........-@%....:%....-%:.......-", ConsoleColor.White),
            ("%-----%%%%-----%+----------%%--------%%%---:---%%%%%%%%%---:--=%%%%%@--::--%%%%-----%-----%---------", ConsoleColor.Cyan),
            ("%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%", ConsoleColor.White),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%@%%%%%%%%%%%%%%%%@%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%", ConsoleColor.DarkGray),
            ("%@%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("", ConsoleColor.Gray),
        };
    }
}
